### ISSUE TITLE
Registration.js

### ISSUE THREAD

**Issue by ColdBrewZZZ** [ColdBrewZZZ/Movie-Team-Project#3]
making the Registration.js. no functionality. making it look like the wireframe. Add routing to App.js

**Comment by Sanek182** [comment]
<img width="1062" alt="Screenshot 2023-07-13 at 14 29 17" src="https://github.com/ColdBrewZZZ/Movie-Team-Project/assets/108419409/92793642-e053-47c0-b514-7ba8f696e865">

**Comment by Sanek182** [comment]
<img width="692" alt="Screenshot 2023-07-13 at 14 30 42" src="https://github.com/ColdBrewZZZ/Movie-Team-Project/assets/108419409/2c315f3c-f66d-4b50-9186-fc961c8249cf">

**Comment by Sanek182** [comment]
<img width="680" alt="Screenshot 2023-07-13 at 14 31 32" src="https://github.com/ColdBrewZZZ/Movie-Team-Project/assets/108419409/84eb7153-35f8-47c5-ba08-75cd89f72f30">

**Comment by Sanek182** [comment]
<img width="675" alt="Screenshot 2023-07-13 at 14 32 00" src="https://github.com/ColdBrewZZZ/Movie-Team-Project/assets/108419409/fbcf602c-a0cb-439d-aae9-7a734e99caee">

**Comment by Sanek182** [comment]
This issue is also done with a basic functional page for four registration steps is ready.
